services:
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: author-service-restapi
    restart: unless-stopped
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    network_mode: host
