apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
  namespace: quote-app
  labels:
    app: author-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: author-service
        image: registry.gitlab.com/berk-karaal/cmpe363-project/author-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: VERSION
          value: "v1.0.0"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8082"
        livenessProbe:
          httpGet:
            path: /api/version
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/version
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
