apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
  namespace: quote-app
  labels:
    app: author-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: registry.gitlab.com/berk-karaal/cmpe363-project/author-service:v0.0.1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: HOST
              value: '0.0.0.0'
            - name: PORT
              value: '8081'
            - name: AUTHOR_SERVICE_URL
              value: 'http://author-service:8082'
          livenessProbe:
            httpGet:
              path: /api/version
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/version
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
