apiVersion: v1
kind: Service
metadata:
  name: author-service
  namespace: quote-app
  labels:
    app: author-service
spec:
  type: ClusterIP
  selector:
    app: author-service
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
